# https://docs.micronaut.io/1.3.3/guide/configurationreference.html
# Rename this file to application.yml and fill data in braces
---
micronaut:
  server:
    port: 8080
    cors:
      enabled: true
---
datasources:
  test:
    url: jdbc:mysql://db/test
    username: (username)
    password: (password)
    driverClassName: com.mysql.cj.jdbc.Driver
