# Rename this file to application.yml and fill data in braces
---
# entrypoint https://docs.micronaut.io/1.3.3/guide/configurationreference.html
micronaut:
  server:
    port: 8080
    cors:
      enabled: true
---
# entrypoint https://guides.micronaut.io/micronaut-security-jwt/guide/index.html
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          refresh-token:
            secret: (secret token)
        signatures:
          secret:
            generator:
              secret: (secret token)
---
datasources:
  test:
    url: jdbc:mysql://db/test
    username: (username)
    password: (password)
    driverClassName: com.mysql.cj.jdbc.Driver
