# https://docs.micronaut.io/1.3.3/guide/configurationreference.html
# Rename this file to application.yml and fill data in braces

micronaut:
  server:
    port: 8090
jooq:
  datasources:
    test:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=Europe/Warsaw
      username: (username)
      password: (password)
      driverClassName: com.mysql.cj.jdbc.Driver
